version: "3.8"

services:
  api:
    image: jihanefettoukh/sentiment-api
    ports:
      - "8000:8000"

  streamlit:
    image: jihanefettoukh/sentiment-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
